site:
  title: PFMG - Kalaba Grammar
  start_page: kalaba::fr/index.adoc
  url: https://example.com

content:
  sources:
    - url: .
      branches: HEAD
      start_path: doc/kalaba

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./doc/build/site

runtime:
  cache_dir: ./doc/.antora-cache

asciidoc:
  attributes:
    bookname: Kalaba
    experimental: ''
    icons: font
